name: cikuraku's notepad
url: http://cikuraku.github.io
description: stream about linux, programing , fund and profit
gems: [jekyll-paginate]

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
